name: Demo
on:
  push:
    branches:
      - demo

jobs:
  changes:
    name: Determine changes
    runs-on: ubuntu-latest
    outputs:
      componentIDs: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            1: 'components/1/**'
            2: 'components/2/**'
            3: 'components/3/**'
            4: 'components/4/**'
            5: 'components/5/**'

  build:
    needs: changes
    if: ${{ fromJSON(needs.changes.outputs.componentIDs).include[0] }} # Skip if no changes
    strategy:
      matrix:
        componentID: ${{ fromJSON(needs.changes.outputs.componentIDs) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 50 } # Some history is required to enable search for most recent git note

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: components/${{ matrix.componentID }}
          build-args: VERSION=${{ github.run_number }}
          tags: ghcr.io/wyarde/demo-gino-keva-${{ matrix.componentID }}:${{ github.run_number }}
          push: true

      - name: Persist metadata
        uses: wyarde/gino-keva-set-action@main
        with:
          key: COMPONENT_${{ matrix.componentID }}
          value: ${{ github.run_number }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: { fetch-depth: 50 } # Some history is required to enable search for most recent git note

      - name: Set component versions in environment
        uses: wyarde/gino-keva-list-action@main
        id: versions

      - id: component_1
        run: docker run --rm ghcr.io/wyarde/demo-gino-keva-1:${{ steps.versions.outputs.COMPONENT_1 }}
      - id: component_2
        run: docker run --rm ghcr.io/wyarde/demo-gino-keva-2:${{ steps.versions.outputs.COMPONENT_2 }}
      - id: component_3
        run: docker run --rm ghcr.io/wyarde/demo-gino-keva-3:${{ steps.versions.outputs.COMPONENT_3 }}
      - id: component_4
        run: docker run --rm ghcr.io/wyarde/demo-gino-keva-4:${{ steps.versions.outputs.COMPONENT_4 }}
      - id: component_5
        run: docker run --rm ghcr.io/wyarde/demo-gino-keva-5:${{ steps.versions.outputs.COMPONENT_5 }}

      - name: Create release
        uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ github.run_number }}
          target_commitish: ${{ github.ref }}
          body: |
            Output component 1: ${{ steps.component_1.outputs.response }}
            Output component 2: ${{ steps.component_2.outputs.response }}
            Output component 3: ${{ steps.component_3.outputs.response }}
            Output component 4: ${{ steps.component_4.outputs.response }}
            Output component 5: ${{ steps.component_5.outputs.response }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
